### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by pyjac** [theresasogunle/RaveJava#1]
What's your plan on writing tests for the library?

Awesome Job though.

**Comment by wunmi-adb** [comment]
It's written.  You can check now.

**Comment by pyjac** [comment]
@theresasogunle While I really commend your effort. Those are not actual tests.

**Comment by pyjac** [comment]
@theresasogunle You can refer to this SO question to give a little background about writing setting up tests in JAVA. https://stackoverflow.com/questions/8751553/how-to-write-a-unit-test

**Comment by wunmi-adb** [comment]
Hi @pyjac  check the folder Rave-Java-Library/src/com/rave/junit/test/. Thank you. If thats not it, do you mind explaining what actual tests are ?

**Comment by pyjac** [comment]
@theresasogunle Ahhh... I see... I was looking at `https://github.com/theresasogunle/Rave-Java-Library/tree/master/src/com/rave/test`.  Quite confused at first.


But you don't want to be hitting external resources with your tests. (i.e rave staging server). Your code should be written in such a way that calls to external services can be mocked.

**Comment by pyjac** [comment]
Also, It's clear what each test case is testing for. 

And some with no assertion. 

Also, You seem not to be accounting for when an exception is thrown in your test.

**Comment by pyjac** [comment]
As an example (not the best) of writing test cases... Check --- (PHP)
https://github.com/andela-joyebanji/OpenSourceEvangelist/blob/master/test/OpenSourceEvangelistFactoryTest.php.. 

So you have a little idea of what I mean.

**Comment by wunmi-adb** [comment]
Okay. Thank you. Got that @pyjac
